server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
  session:
    store-type: none

# 是否启用security
#security:
#  basic:
#    enabled: false
lllockkk:
  security:
    browser:
      loginPage: /login.html
      loginType: JSON




